#! /bin/sh -f

echo "Running the GNU autotools.  Please be patient ..."

autoreconf --install --force

if [ $? -eq 0 ]; then

  echo
  echo "Bootstrap complete.  You can now run the configure script."
  echo
  exit 0

else

  echo
  echo "An error occured while running the GNU autotools."
  echo "Please contact lawrence.toomey@csiro.au"
  echo
  exit -1

fi

